### ISSUE TITLE
raise AddressValueError("Expected 4 octets in %r" % ip_str)

### ISSUE THREAD

**Issue by acbekoac** [bojanisc/quicmap#2]
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

##############

./quicmap/bin/python -V
Python 3.11.2

##############

./quicmap/bin/python ./quicmap/quicmap.py -p 443 mandalore.fsmb.rwth-aachen.de.
Traceback (most recent call last):
  File "/home/acbeko/git_tools/./quicmap/quicmap.py", line 266, in <module>
    hosts, ports = parse_arguments()
                   ^^^^^^^^^^^^^^^^^
  File "/home/acbeko/git_tools/./quicmap/quicmap.py", line 145, in parse_arguments
    hosts = parse_hosts(host_spec)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acbeko/git_tools/./quicmap/quicmap.py", line 97, in parse_hosts
    ipaddress.IPv4Address(start.strip()), ipaddress.IPv4Address(end.strip())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 1315, in __init__
    self._ip = self._ip_int_from_string(addr_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 1202, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'mandalore.fsmb.rwth'

##############

is executed using IPv4- or IPv6 address

./quicmap/bin/python ./quicmap/quicmap.py -p 443 134.130.104.122
100%|...| 1/1 [00:05<00:00,  5.00s/it]

./quicmap/bin/python ./quicmap/quicmap.py -p 443 2a00:8a60:61d::140
100%|...| 1/1 [00:05<00:00,  5.00s/it]

**Comment by bojanisc** [comment]
Thanks - confirming the issue, will be fixed soon.

**Comment by francutura** [comment]
Fixed in [commit](https://github.com/bojanisc/quicmap/commit/1352ddd532b9b1520b8233c5ebcec8411592b754)
